/**
 * lib/checkray-core/safe-wording.ts
 *
 * Disclaimer and safe-wording constants shared across all CheckRay surfaces.
 *
 * RULE: The disclaimer MUST appear on every surface that shows a Ray result.
 * Use ensureDisclaimer() before returning any report from the API.
 */

export const ANALYSIS_DISCLAIMER =
  "Ray can be wrong. Results are informational only and not legal, financial, medical, or professional advice. Verify important decisions through official sources."

export const EXTENSION_DISCLAIMER =
  "Ray can be wrong. Verify through official sources."

export const EMAIL_DISCLAIMER =
  "This analysis was generated by Ray, an AI assistant. It is informational only and not professional advice. Always verify through official sources."

/**
 * Ensure a report has a non-empty disclaimer.
 * Falls back to the canonical ANALYSIS_DISCLAIMER if missing.
 */
export function ensureDisclaimer(disclaimer: string | undefined | null): string {
  if (disclaimer && disclaimer.trim().length > 0) return disclaimer
  return ANALYSIS_DISCLAIMER
}
